### ISSUE TITLE
LaunchTemplate makes properties in AWS::EC2::Instance resource no longer required

### ISSUE THREAD

**Issue by nand0p** [stelligent/cfn_nag#136]
With the new `AWS::EC2::LaunchTemplate` resource, previously required properties in `AWS::EC2::Instance` are no longer required, when `LaunchTemplateId` is specified.

```
  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !ImportValue 'DevSecOps-JenkinsSubnet'
          DeviceIndex: 0
          GroupSet:
            - !ImportValue 'DevSecOps-JenkinsSecurityGroup'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      LaunchTemplate:
        LaunchTemplateId: !Ref JenkinsLaunchTemplate
        Version: 1
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M
```
