### ISSUE TITLE
Checking Parameters via Ref

### ISSUE THREAD

**Issue by ALeonard9** [stelligent/cfn_nag#142]
Hello and thank you for your time.

I am implementing cfn_nag as part of a infrastructure pipeline and love the ability to create my own rules. I am running into a particular issue and want to see how best to address it.

Let's say I'm checking if a property is true on a resource. If I have that setting referenced in a parameter, can it still be checked?

```yaml
---
Parameters:
  encryption:
    Type: String
    default: 'false'
    
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      StorageEncrypted: 
        - Ref: encryption

```
