### ISSUE TITLE
Allowing * resources

### ISSUE THREAD

**Issue by danbryan** [stelligent/cfn_nag#152]
I was hoping someone could either school me in cf, or help me understand if there is a way to limit the reporting of * resources to a specific depth.  It seems like any policy that contains a * is a warning.

Take this policy for example:
````
rotateAmiPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "logs:CreateLogGroup"
          Resource:
            Fn::Join: [ "", [ "arn:",  { "Ref" : "AWS::Partition" }, ":logs:", { "Ref" : "AWS::Region" }, ":", { "Ref" : "AWS::AccountId" }, ":log-group:/aws/lambda/", { "Ref" : rotateAmiFunction } ] ]
        - Effect: Allow
          Action: "logs:CreateLogStream"
          Resource:
            Fn::Join: [ "", [ "arn:",  { "Ref" : "AWS::Partition" }, ":logs:", { "Ref" : "AWS::Region" }, ":", { "Ref" : "AWS::AccountId" }, ":log-group:/aws/lambda/*" ] ]
````

because it has * it shows up as a warning, but AFAIK there is no way to dynamically add  the exact logstream, ie

````
"2019/02/04/[$LATEST]e727fb1e34f346daba8e02c1ea04cdb8"
````

should i just learn to be ok with warnings, and let our ci/cd processes push changesets for template files with warnings? Or is there a way I can say, if it's a W13 and the line is 'complicated enough', then no warning.
