### ISSUE TITLE
False Positive: Rule failing when pulling from secrets manager

### ISSUE THREAD

**Issue by paul-nelson-baker** [stelligent/cfn_nag#201]
It looks like there was a pull about an hour or so ago. It immediately blocks our RDS cluster that uses SecretsManager directly and doesn't use parameters, but uses [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html).

[Here is the change that did it](https://github.com/stelligent/cfn_nag/commit/b48878ba61221737f2922d9be756a190311b2f7c)

And here is a pseudo snippet of what our template looks like

```yaml
  RDSDatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBSubnetGroupName: !Ref RDSSubnetGroup 
      DBClusterIdentifier: !Ref RDSClusterIdentifier
      Engine: aurora
      EngineMode: provisioned
      StorageEncrypted: true
      KmsKeyId: !ImportValue GenericRDSKey
      MasterUsername: '{{resolve:secretsmanager:/DBA/rds/masteruser:SecretString:username}}'
      MasterUserPassword: '{{resolve:secretsmanager:/DBA/rds/masteruser:SecretString:password}}'
      VpcSecurityGroupIds:
        - !Ref RDSSecurityGroup
      DBClusterParameterGroupName: !Ref RDSClusterParameterFamilyAurora
```
