### ISSUE TITLE
Error checking security in template `block in audit_impl': undefined method `to_i'

### ISSUE THREAD

**Issue by littleJabiel** [stelligent/cfn_nag#295]
Hi, checking security of a cloudformation template I get the following error:

```
Running command cfn_nag_scan --input-path ${CLOUDFORMATION_TEMPLATE_NAME} 2>&1 
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rules/SecurityGroupIngressAllProtocolsRule.rb:32:in `block in audit_impl': undefined method `to_i' for {"Ref"=>"RDSTransportProtocol"}:Hash (NoMethodError) 
Did you mean?  to_s 
               to_a 
               to_h 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rules/SecurityGroupIngressAllProtocolsRule.rb:31:in `select' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rules/SecurityGroupIngressAllProtocolsRule.rb:31:in `audit_impl' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rules/base.rb:19:in `audit' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rule_loader.rb:92:in `block in filter_rule_classes' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rule_loader.rb:85:in `each' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rule_loader.rb:85:in `filter_rule_classes' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/custom_rule_loader.rb:55:in `execute_custom_rules' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag.rb:82:in `audit' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag.rb:60:in `block in audit_aggregate_across_files' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag.rb:57:in `each' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag.rb:57:in `audit_aggregate_across_files' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag.rb:31:in `audit_aggregate_across_files_and_render_results' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag_executor.rb:47:in `execute_aggregate_scan' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/lib/cfn-nag/cfn_nag_executor.rb:27:in `scan' 
    from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.39/bin/cfn_nag_scan:11:in `<top (required)>' 
    from /root/.rbenv/versions/2.6.3/bin/cfn_nag_scan:23:in `load' 
    from /root/.rbenv/versions/2.6.3/bin/cfn_nag_scan:23:in `<main>' 
```

The cloudformation code related with the error:

```
  IngressRuleSQLSecurityGroupBaseRDS:
    Condition: RDSConnection
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue: !Sub "${BaseSecurityGroupStackName}:RDSBaseServiceSecurityGroupId"
      Description: "Allow instace SQL access to rds instances"
      IpProtocol: !Ref RDSTransportProtocol
      FromPort: !Ref RDSPort
      ToPort: !Ref RDSPort
      SourceSecurityGroupId: !Ref InstanceSecurityGroup`
```

RDSTransportProtocol is a template parameter. 

could you help me please? Am I doing something wrong?

thanks
