### ISSUE TITLE
CommaDelimitedList failing schema validation

### ISSUE THREAD

**Issue by rdpa** [stelligent/cfn_nag#304]
One of our templates is seemingly incorrectly failing schema validation. Here is the affected snippet:

```yaml
Parameters:
  ManagedPolicyArns:
    Type: CommaDelimitedList
    Default: ''

Resources:
  Group:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns: !Ref ManagedPolicyArns
```

Here's the error:

```
| FAIL FATAL
|
| Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/Group/Properties/ManagedPolicyArns] not a sequence.>]
```

What i'd expect to happen here is that cfn_lint recognizes that a CommaDelimitedList is a valid substitute for a sequence.
