### ISSUE TITLE
Crashes when using Fn::If to decide a set of Resource Properties

### ISSUE THREAD

**Issue by JoseRolles** [stelligent/cfn_nag#334]
Cannot use Fn::If to decide a set of properties for a resource. However, the template creates a stack successfully.

For example, the following template will crash in cfn_nag.
```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
    RestoreSecretString:
        Type: String
        NoEcho: true
        Default: none
Conditions:
    IsNone: !Or
        - !Equals
            - !Ref RestoreSecretString
            - none
        - !Equals
            - !Ref RestoreSecretString
            - ""
Resources:
    AppDbSecret:
        Type: AWS::SecretsManager::Secret
        DeletionPolicy: Retain
        Properties: !If
            - IsNone
            - Description: 'New'
              GenerateSecretString:
                SecretStringTemplate: '{"username": "test-user"}'
                GenerateStringKey: "password"
                PasswordLength: 30
                ExcludeCharacters: '"@/\'
            - Description: 'Restore'
              SecretString: !Ref 'RestoreSecretString'
```

The error output:
```
/usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/model/model_element.rb:93:in `instance_variable_get': `@fn::If=' is not allowed as an instance variable name (NameError)
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/model/model_element.rb:93:in `method_missing'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:182:in `block in assign_fields_based_upon_properties'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:180:in `each'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:180:in `assign_fields_based_upon_properties'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:138:in `block in transform_hash_into_model_elements_with_numbers'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:130:in `each'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:130:in `transform_hash_into_model_elements_with_numbers'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:78:in `parse_without_parameters'
        from /usr/local/bundle/gems/cfn-model-0.4.9/lib/cfn-model/parser/cfn_parser.rb:42:in `parse'
        from /usr/local/bundle/gems/cfn-nag-0.4.56/lib/cfn-nag/cfn_nag.rb:79:in `audit'
        from /usr/local/bundle/gems/cfn-nag-0.4.56/lib/cfn-nag/cfn_nag_executor.rb:56:in `scan_file'
        from /usr/local/bundle/gems/cfn-nag-0.4.56/lib/cfn-nag/cfn_nag_executor.rb:36:in `execute_file_or_piped_scan'
        from /usr/local/bundle/gems/cfn-nag-0.4.56/lib/cfn-nag/cfn_nag_executor.rb:27:in `scan'
        from /usr/local/bundle/gems/cfn-nag-0.4.56/bin/cfn_nag:11:in `<top (required)>'
        from /usr/local/bundle/bin/cfn_nag:23:in `load'
        from /usr/local/bundle/bin/cfn_nag:23:in `<main>'
```
