### ISSUE TITLE
ElasticLoadBalancerV2AccessLoggingRule new error

### ISSUE THREAD

**Issue by EloyRedondo** [stelligent/cfn_nag#339]
Hi,
After some change in the repository in the last month, I started having the following error when executing cfn_nag:
```
docker run --rm -v /home/ered/repositories/codecommit/vy-cf-app-stack-product:/templates stelligent/cfn_nag /templates/vy-cf-app-stack.template && echo -e "\e[32m"[OK]"\e[39m" || (echo -e "\e[31m"[ERROR]"\e[39m" && exit 1)
/usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:39:in `block in missing_access_logs?': no implicit conversion of String into Integer (TypeError)
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:38:in `each'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:38:in `find'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:38:in `missing_access_logs?'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:22:in `block in audit_impl'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:21:in `select'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/ElasticLoadBalancerV2AccessLoggingRule.rb:21:in `audit_impl'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rules/base.rb:19:in `audit'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rule_loader.rb:92:in `block in filter_rule_classes'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rule_loader.rb:85:in `each'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rule_loader.rb:85:in `filter_rule_classes'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/custom_rule_loader.rb:55:in `execute_custom_rules'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/cfn_nag.rb:84:in `audit'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/cfn_nag_executor.rb:56:in `scan_file'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/cfn_nag_executor.rb:36:in `execute_file_or_piped_scan'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/lib/cfn-nag/cfn_nag_executor.rb:27:in `scan'
	from /usr/local/bundle/gems/cfn-nag-0.4.63/bin/cfn_nag:11:in `<top (required)>'
	from /usr/local/bundle/bin/cfn_nag:23:in `load'
	from /usr/local/bundle/bin/cfn_nag:23:in `<main>'
```

My resource is defined like this:
```
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        !If
        - EnableLogsPublicLB
        -
          - Key: access_logs.s3.enabled
            Value: 'true'
          - Key: access_logs.s3.bucket
            Value:
              Fn::ImportValue: !Sub '${Project}-${ApplicationGroup}-${Environment}-${BucketLogsNameSuffix}'
          - Key: access_logs.s3.prefix
            Value: loadbalancer
        -
          - Key: access_logs.s3.enabled
            Value: 'false'
```

I don't know what the problem may be, if you could help me I would appreciate it very much.
