### ISSUE TITLE
Failing with `F34` even if it is not true

### ISSUE THREAD

**Issue by guusvw** [stelligent/cfn_nag#352]
We discovered an issue with rule `F34` which should trigger if you set a plaintext password or a reference to a parameter with `NoEcho` AND a default value.

In our case we're having a switch in the `MasterUserPassword` to use `"AWS::NoValue"` if we're running the CloudFormation template in a case where we don't want to restore from a snapshot or using a parameter value, if we want to restore from a snapshot.
The parameter value is setup to be `NoEcho` but WITHOUT a default value.
When I'm using only the reference to the `DBPwd` the warning do not appears, so I'm considering that the issue is triggered by the `If` statement or the reference to `AWS::NoValue"`.

Definition of the parameter:
```yaml
Parameters:
  DBPwd:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 10
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9\#]*$
```

Definition of the RDS resource:
```yaml
  RDSCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Snapshot
    Properties:
      DatabaseName: "database"
      MasterUsername: !If [RestoreFromSnapshot, !Ref "AWS::NoValue", !Ref DBUser]
      MasterUserPassword: !If [RestoreFromSnapshot, !Ref "AWS::NoValue", !Ref DBPwd]
```

Occurring error:
```
------------------------------------------------------------------------------------------------------------------------
| FAIL F34
|
| Resources: ["RDSCluster"]
| Line Numbers: [66]
|
| RDS DB Cluster master user password must not be a plaintext string or a Ref to a NoEcho Parameter with a Default value.
------------------------------------------------------------
```
