### ISSUE TITLE
W45 (ApiGateway should have access logging configured) must include the AWS::ApiGateway::Stage

### ISSUE THREAD

**Issue by lhgomes** [stelligent/cfn_nag#402]
The W45 rule also needs to check the Stage, since the AccessLogSetting can also be defined at Stage level: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-accesslogsetting

If the AccessLogSetting was defined at Stage level, the warning should not trigger.

Sample:
```
  authapiDeploymentStagev1B9C73559:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: authapi291673A5
      AccessLogSetting:
        DestinationArn:
          Fn::Join:
            - ":"
            - - arn:aws:logs
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - log-group
              - Fn::Join:
                  - /
                  - - Fn::Join:
                        - _
                        - - API-Gateway-Execution-Logs
                          - Ref: authapi291673A5
                    - v1
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      DeploymentId:
        Ref: authapiDeployment185424326dae743334fb8aafc4d889570eef3f17
      Description: Default stage for AuthApi
      MethodSettings:
        - CachingEnabled: false
          HttpMethod: "*"
          LoggingLevel: ERROR
          ResourcePath: /*
      StageName: v1
    Metadata:
      aws:cdk:path: AuthApiStack/auth-api/DeploymentStage.v1/Resource
```

Related with #300
