### ISSUE TITLE
Undefined method `ipProtocol' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by chethanabhaskara** [stelligent/cfn_nag#405]
I'm trying to run cfn_nag_scan into a cloud formation and running into this problem - 
```
Traceback (most recent call last):
	22: from /usr/local/bin/cfn_nag_scan:23:in `<main>'
	21: from /usr/local/bin/cfn_nag_scan:23:in `load'
	20: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/bin/cfn_nag_scan:11:in `<top (required)>'
	19: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag_executor.rb:29:in `scan'
	18: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag_executor.rb:49:in `execute_aggregate_scan'
	17: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag.rb:34:in `audit_aggregate_across_files_and_render_results'
	16: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag.rb:64:in `audit_aggregate_across_files'
	15: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag.rb:64:in `each'
	14: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag.rb:67:in `block in audit_aggregate_across_files'
	13: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/cfn_nag.rb:90:in `audit'
	12: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rule_loader.rb:54:in `execute_custom_rules'
	11: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rule_loader.rb:63:in `filter_rule_classes'
	10: from /usr/lib/ruby/2.5.0/set.rb:338:in `each'
	 9: from /usr/lib/ruby/2.5.0/set.rb:338:in `each_key'
	 8: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rule_loader.rb:70:in `block in filter_rule_classes'
	 7: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/base.rb:19:in `audit'
	 6: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:26:in `audit_impl'
	 5: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:26:in `select'
	 4: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:27:in `block in audit_impl'
	 3: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:27:in `select'
	 2: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:28:in `block (2 levels) in audit_impl'
	 1: from /var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:52:in `violating_egress'
/var/lib/gems/2.5.0/gems/cfn-nag-0.5.21/lib/cfn-nag/custom_rules/SecurityGroupEgressAllProtocolsRule.rb:44:in `negative_1_protocol?': undefined method `ipProtocol' for nil:NilClass (NoMethodError)
```
The relevant json causing this issue is 
```
     SecurityGroupEgress:
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0
        - !If
          - MicroInt
          - IpProtocol: '-1'
            FromPort: '-1'
            ToPort: '-1'
            CidrIp: !FindInMap [AccountTypeCIDRMap, micro-int, California]
          - {}
```
Setting the IpProtocol to -1 is causing the issue in specifc. Could you help me with this?
