### ISSUE TITLE
Requires optional key for V2 LoadBalancer

### ISSUE THREAD

**Issue by claesjonsson** [stelligent/cfn_nag#44]
With the V2 LoadBalancer with type _network_ you can specify **_either_** `Subnets` or `SubnetMappings` under the Properties key, but currently the model requires `Subnets`.

CloudFormation snippet:

```yaml
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      SubnetMappings:
        - AllocationId: 'eipalloc-xxxxxx'
          SubnetId: !Ref Subnet1ID
        - AllocationId: 'eipalloc-xxxxx
          SubnetId: !Ref Subnet2ID
```

Result:

````json
{
  "failure_count": 1,
  "violations": [
    {
      "id": "FATAL",
      "type": "FAIL",
      "message": "Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/NetworkLoadBalancer/Properties] key 'Subnets:' is required.>]",
      "logical_resource_ids": null
    }
  ]
}
```
