### ISSUE TITLE
W40 incorrectly triggered with egress of localhost

### ISSUE THREAD

**Issue by candrews** [stelligent/cfn_nag#447]
Given this cloudformation template:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test
Resources:
  FileSystemSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: FileSystem Security Group
      SecurityGroupEgress:
        - Description: Disallow all IPv6 egress
          IpProtocol: '-1'
          CidrIpv6: ::1/128
        - Description: Disallow all IPv4 egress
          IpProtocol: '-1'
          CidrIp: 127.0.0.1/32
```
cfn_nag should not return a warning because the `CidrIP` is localhost, see #289
However, it does return:
```
| WARN W40
|
| Resources: ["FileSystemSecurityGroup"]
| Line Numbers: [6]
|
| Security Groups egress with an IpProtocol of -1 found

```

I'm using cfn_nag 0.5.54.
