### ISSUE TITLE
W66 incorrectly triggered

### ISSUE THREAD

**Issue by candrews** [stelligent/cfn_nag#448]
Given this template:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test
Resources:
  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Network
          Value: Public
  InboundHTTPPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 80
        To: 80
```

I get this warning (using cfn_nag 0.5.54):
```
| WARN W66
|
| Resources: ["InboundHTTPPublicNetworkAclEntry"]
| Line Numbers: [12]
|
| To avoid opening all ports for Allow rules, EC2 NetworkACL Entry Protocol should be either 6 (for TCP), 17 (for UDP), 1 (for ICMP), or 58 (for ICMPv6, which must include an IPv6 CIDR block, ICMP type, and code).
```

Protocol 6 is being used so the warning is clearly incorrect.
