### ISSUE TITLE
W72 incorrectly triggered due to not handling IPv4 and IPv6 separately

### ISSUE THREAD

**Issue by candrews** [stelligent/cfn_nag#453]
Given this template:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test
Resources:
  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackName'
        - Key: Network
          Value: Public
  InboundHTTPPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      Egress: false
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: 80
        To: 80
  InboundHTTPPublicNetworkAclEntryIPv6:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 200
      Protocol: 6
      RuleAction: allow
      Egress: false
      Ipv6CidrBlock: '::/0'
      PortRange:
        From: 80
        To: 80
```
W72 should not be triggered as there are no overlapping ports.

However, with cfn_nag 0.5.58:
```
| WARN W72
|
| Resources: ["InboundHTTPPublicNetworkAclEntry", "InboundHTTPPublicNetworkAclEntryIPv6"]
| Line Numbers: [14, 26]
|
| NetworkACL Entries are reusing or overlapping ports which may create ineffective rules.
```

The rule needs to consider IPv4 and IPv6 separately.
