### ISSUE TITLE
Description is an invalid Resource Attribute

### ISSUE THREAD

**Issue by OEMarshall** [stelligent/cfn_nag#477]
The linter flags **Description** is an invalid resource attribute for several cloud formation resources, but there are [several](https://docs.aws.amazon.com/es_es/powershell/latest/reference/items/New-EBApplication.html) [counterexamples](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-elasticbeanstalk.html) of this property being used by AWS for these resources.
- [ ] AWS::IAM::Role
- [ ] AWS::IAM::ManagedPolicy
- [ ] AWS::CodePipeline::Pipeline
- [ ] AWS::S3::BucketPolicy
- [ ] AWS::S3::Bucket
- [ ] AWS::ElasticBeanstalk::Application
- [ ] AWS::ElasticBeanstalk::ApplicationVersion
- [ ] AWS::ElasticBeanstalk::Environment

What's the best way to "silence" this rule? Create a new rule, delete the relevant rule or create an exception?

**Comment by OEMarshall** [comment]
Nevermind found this in the readme https://github.com/stelligent/cfn_nag#per-resource-rule-suppression

**Comment by OEMarshall** [comment]
Nevermind

**Comment by erickascic** [comment]
@OEMarshall can you provide an example input/output? i'm not sure that i'm following.  which rule is this? cfn_nag definnitely shouldn't complain about Description on an IAM::Role

**Comment by OEMarshall** [comment]
Here are the yml snippets for this and the error messages. 
`[cfn-lint] E3001: Invalid resource attribute Description for resource EBInstanceProfile`
`[cfn-lint] E3001: Invalid resource attribute Description for resource EBEnviroment`
`[cfn-lint] E3001: Invalid resource attribute Description for resource ToolChainRole`

```yml
 EBInstanceProfile:
    Description: Creating Amazon EC2 instance profile for AWS Elastic Beanstalk
    Properties:
      Path: /
      Roles:
        - !Ref 'EBInstanceProfileRole'
    Type: AWS::IAM::InstanceProfile
EBEnvironment:
    Description: The AWS Elastic Beanstalk deployment group where the application is deployed, which is made up of the Amazon EC2 Linux instances launched for this project.
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'EBApplication'
      EnvironmentName: !Ref 'EBApplication'
      Description: The application to be deployed to the environment.
      TemplateName: !Ref 'EBConfigurationTemplate'
      VersionLabel: !Ref 'EBApplicationVersion'
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref 'EBInstanceProfile'
```

```yml
ToolChainRole:
    DeletionPolicy: Delete
    Description: Creating toolchain role in IAM for Amazon EC2 instances
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSCodeCommitFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSCodeBuildAdminAccess'
      Path: /
      PermissionsBoundary: !Ref 'PermissionsBoundaryPolicy'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - kms:GenerateDataKey*
                Effect: Allow
                Resource: '*'
          PolicyName: ToolChainWorkerPolicy
      RoleName: !Sub 'Worker-${ProjectId}-${AWS::StackName}-ToolChain'
    Type: AWS::IAM::Role
```
