### ISSUE TITLE
W72 is not properly suppressed

### ISSUE THREAD

**Issue by phelewski** [stelligent/cfn_nag#483]
Working on a new networking template and came across an issue with Rule W72. I have 2 NACL entries for port 22 (ssh) and 2 different IP ranges. The W72 rule seems to be properly triggered and catches that there are 2 `AWS::EC2::NetworkAclEntry` resources using the same port range, however, after adding an exception with `rules_to_suppress` for both resources, the warning still comes through when the scan is run.

I can create this "bug/feature" with the following template:
``` yaml
---
Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
  CIDR1:
    Type: String
    Default: 10.10.0.0/27
  CIDR2:
    Type: String
    Default: 10.20.0.0/27

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      LogGroupName: FlowLogsGroup
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL

  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC

  NetworkAclEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W72
            reason: Specifying 2 rules for SSH access from specific IP ranges
    Properties:
       NetworkAclId: !Ref NetworkAcl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: !Ref CIDR1
       PortRange:
         From: 22
         To: 22

  NetworkAclEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W72
            reason: Specifying 2 rules for SSH access from specific IP ranges
    Properties:
       NetworkAclId: !Ref NetworkAcl
       RuleNumber: 200
       Protocol: 6
       RuleAction: allow
       CidrBlock: !Ref CIDR2
       PortRange:
         From: 22
         To: 22
```
``` bash
------------------------------------------------------------
cfn_nag.yaml
------------------------------------------------------------------------------------------------------------------------
| WARN W72
|
| Resources: ["NetworkAclEntry1", "NetworkAclEntry2"]
| Line Numbers: [35, 52]
|
| NetworkACL Entries are reusing or overlapping ports which may create ineffective rules.

Failures count: 0
Warnings count: 2
```

I'm able to get past the improperly suppressed rule by adding W72 to the blacklist.

Upon further testing there may be an issue with the underlying rule itself. If I don't use the intrinsic function `Reference` for the `NetworkAclId`, then rule W72 doesn't catch the duplicate port entries.

``` yaml
---
Parameters:
  CIDR1:
    Type: String
    Default: 10.10.0.0/27
  CIDR2:
    Type: String
    Default: 10.20.0.0/27

Resources:
  NetworkAclEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: acl-01234abcd5678efgh
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: !Ref CIDR1
       PortRange:
         From: 22
         To: 22

  NetworkAclEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: acl-01234abcd5678efgh
       RuleNumber: 200
       Protocol: 6
       RuleAction: allow
       CidrBlock: !Ref CIDR2
       PortRange:
         From: 22
         To: 22
```
``` bash
------------------------------------------------------------
cfn_nag.yaml
------------------------------------------------------------
Failures count: 0
Warnings count: 0
```
