### ISSUE TITLE
W12 doesn't make sense

### ISSUE THREAD

**Issue by Slooz** [stelligent/cfn_nag#490]
W12 is issued for the following template:
```yaml
Resources:
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: foo
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: cloudwatch:GetAuthorizationToken
            Resource: "*"
```

```
| WARN W12
|
| Resources: ["Policy"]
| Line Numbers: [3]
|
| IAM policy should not allow * resource
```

But the only valid value for the `Resource` property of the `cloudwatch:GetAuthorizationToken` action is `*`. See [Actions, resources, and condition keys for Amazon Elastic Container Registry - AWS Identity and Access Management](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerregistry.html#amazonelasticcontainerregistry-GetAuthorizationToken). This warning doesn't make sense.
