### ISSUE TITLE
Potential mis- (or incomplete) report of F18 and F21

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [stelligent/cfn_nag#497]
**Issues search**:  I searched past issues for `F18`, `F21` and `Principal`. The closest hit I got was https://github.com/stelligent/cfn_nag/issues/9.

Now my issue...

I'm getting

```
| FAIL F18
|
| Resources: ["TopicPolicy"]
| Line Numbers: [100]
|
| SNS topic policy should not allow * principal
```

and 

```
| FAIL F21
|
| Resources: ["QueuePolicy"]
| Line Numbers: [100]
|
| SQS Queue policy should not allow * principal
```

for policies for which I have Principal containing an `*` but also a `Condition`. Am I wrong to think that the condition should be enough to shut the warning up? Or would analysis be too complex (as far as `cnf_nag` is concerned), in this particular case, and we should thus use the exception "metadata"?

[it might be lack of knowledge on AWS, on my behalf, I acknowledge that]

**Note**

My resources are expressed as:

```
  TopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Resource:
            - !Ref SNSTopic
          Effect: Allow
          Principal: "*"
          Action:
            - sns:Publish
          Condition:
            StringEquals:
              AWS:SourceAccount: !Ref MySourceAccount
      Topics:
        - Ref: SNSTopic
```

and 

```
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Resource:
            - !GetAtt MyQueue.Arn
          Effect: Allow
          Principal: "*"
          Action:
            - sqs:SendMessage
          Condition:
            ArnEquals:
              aws:SourceArn:
                - !Ref MyTopic
```

respectively.

Thanks much for your help and the excellent tool.
