### ISSUE TITLE
AWS::KinesisFirehose::DeliveryStream - SSE

### ISSUE THREAD

**Issue by dscpinheiro** [stelligent/cfn_nag#521]
Kinesis Firehose recently added support for setting Server-Side Encryption of a delivery stream via CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-deliverystreamencryptionconfigurationinput.html). Previously, this was only possible by invoking the `start-delivery-stream-encryption` API (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/firehose/start-delivery-stream-encryption.html).

This encryption should be set when the delivery stream type is set to `DirectPut` (i.e. producer applications access the delivery stream directly). This property is not needed if the type is `KinesisStreamAsSource`, since _"when you configure a Kinesis data stream as the data source of a Kinesis Data Firehose delivery stream, Kinesis Data Firehose no longer stores the data at rest. Instead, the data is stored in the data stream"_ (https://docs.aws.amazon.com/firehose/latest/dev/encryption.html#sse-with-data-stream-as-source).

Once the rule is created, the following resource would throw a warning:
```yaml
DeliveryStreamUnencrypted:
  Type: AWS::KinesisFirehose::DeliveryStream
  Properties:
    DeliveryStreamType: DirectPut
    ExtendedS3DestinationConfiguration:
      BucketARN: output-bucket-arn
      RoleARN: firehose-role-arn
```

While these wouldn't:
```yaml
DeliveryStreamAwsKey:
  Type: AWS::KinesisFirehose::DeliveryStream
  Properties:
    DeliveryStreamEncryptionConfigurationInput:
      KeyType: AWS_OWNED_CMK
    DeliveryStreamType: DirectPut
    ExtendedS3DestinationConfiguration:
      BucketARN: output-bucket-arn
      RoleARN: firehose-role-arn

DeliveryStreamCustomKey:
  Type: AWS::KinesisFirehose::DeliveryStream
  Properties:
    DeliveryStreamEncryptionConfigurationInput:
      KeyARN: customer-key-arn
      KeyType: CUSTOMER_MANAGED_CMK
    DeliveryStreamType: DirectPut
    ExtendedS3DestinationConfiguration:
      BucketARN: output-bucket-arn
      RoleARN: firehose-role-arn

DeliveryStreamKds:
  Type: AWS::KinesisFirehose::DeliveryStream
  Properties:
    DeliveryStreamType: KinesisStreamAsSource
    ExtendedS3DestinationConfiguration:
      BucketARN: output-bucket-arn
      RoleARN: firehose-role-arn
    KinesisStreamSourceConfiguration:
      KinesisStreamARN: kinesis-stream-arn
      RoleARN: firehose-role-arn
```
