### ISSUE TITLE
Support AWS Lambda Container Feature

### ISSUE THREAD

**Issue by atarynin** [stelligent/cfn_nag#532]
The CF template `cloudFormation/templates/lambda.yaml`
```
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaFunctionS3Key:
    Description: The key in the S3 bucket that contains the src code of the Python script
    Type: String
  LambdaRole:
    Description: Name of the Lambda role
    Type: String
  LambdaFunctionName:
    Description: The name of the lambda function
    Type: String
  LambdaSqsSource:
    Description: The name of the source SQS queue
    Type: String
  LambdaMemorySize:
    Description: Memory size for lambda.
    Type: String
    Default: "256"

Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ImageUri: <image_url>
      FunctionName: !Ref LambdaFunctionName
      MemorySize: !Ref LambdaMemorySize
      Role: !Ref LambdaRole
      Timeout: 30
      ReservedConcurrentExecutions: 5
      PackageType: 'Image'
  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName:
        Fn::GetAtt:
          - "LambdaFunction"
          - "Arn"
      EventSourceArn: !Ref LambdaSqsSource
```
fails on the validation step with such error:
```
cloudFormation/templates/lambda.yaml
------------------------------------------------------------------------------------------------------------------------
[31m| FAIL FATAL[0m
[31m|[0m
[31m| Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/LambdaFunction/Properties] key 'Handler:' is required.>, #<Kwalify::ValidationError: [/Resources/LambdaFunction/Properties] key 'Runtime:' is required.>][0m

Failures count: 1
Warnings count: 0
```

Seems like cfn_nag tool doesn't support a [new AWS functionality](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) yet. 
From AWS doc:
`You set the package type to Image if the deployment package is a container image. For a container image, the code property must include the URI of a container image in the Amazon ECR registry. You do not need to specify the handler and runtime properties.`
link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by atarynin** [comment]
I tried to skip the validation by adding
```
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: FATAL
            reason: "Temp disable all checks"
```
but seems like a can't skip that kind of rule :)
