### ISSUE TITLE
Validation Error on Docker Lambda Functions

### ISSUE THREAD

**Issue by dontirun** [stelligent/cfn_nag#546]
Lambda functions do not require a Handler and a Runtime when using a docker image. cfn_nag throws a fatal error when a valid Lambda function with a Docker image is defined

Error:
```
| FAIL FATAL
|
| Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/rLambda/Properties] key 'Handler:' is required.>, #<Kwalify::ValidationError: [/Resources/rLambda/Properties] key 'Runtime:' is required.>,
```

Example Lambda:

```yaml
rLambda:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      ImageUri:
        Fn::Join:
          - ""
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - "."
            - Ref: AWS::URLSuffix
            - /aws-cdk/assets:6cb05e256a344655e2fc54d249297824285462a277ccaca800b188b804268b13
    Role:
      Fn::GetAtt:
        - rLambdaServiceRoleA90D9137
        - Arn
    MemorySize: 1024
    PackageType: Image
    Timeout: 300
```
