### ISSUE TITLE
Cloud Formation overload "ports" parameters for icmp protocol

### ISSUE THREAD

**Issue by vchepkov** [stelligent/cfn_nag#629]
cfn_nags generates W27 warning for a code fragment:
```
    SecurityGroupIngress:
        - Description: Allow ICMP ping
          IpProtocol: icmp
          FromPort: 8
          ToPort: 0
          CidrIp: "10.0.0.0/8"
```

Cloud Formation repurposed ports attributes as "type and code" for icmp protocol, so the warning about port ranges should be suppressed
