### ISSUE TITLE
Custom rules not working as expected

### ISSUE THREAD

**Issue by drmmarsunited** [stelligent/cfn_nag#96]
I've been doing some testing with writing my own custom rules, but also with a custom rule that's been committed to the repo.  Let's focus on the EbsVolumeHasSseRule.rb rule.

Here is my test CFN template (YAML):

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GetTenantOwnerTable:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Encryption: true
      Size: 100
      VolumeType: magnetic
```

I've run a few test cases here, however, they all result in a failure condition:

1. Encryption property set to true or "true" (as in the above code example) [No failure expected, but received]
2. Encryption property completely omitted [Failure expected and received]
3. Encryption property set to false or "false" [Failure expected and received]

Maybe I'm missing something obvious, but looking at the failure conditions in the rule:
```
def audit_impl(cfn_model)
    violating_volumes = cfn_model.resources_by_type('AWS::EC2::Volume').select do |volume|
      volume.encrypted.nil? || volume.encrypted.to_s.downcase == 'false'
    end

    violating_volumes.map { |violating_user| violating_user.logical_resource_id }
  end
```

 I would expect test 1 from above to not generate any warnings/failures, but it consistently does.  This same logic issue is carrying through to other custom rules I am writing and I feel like I'm missing something.

Can you help shed any light on the issue here?
